# Generated by Django 4.2.1 on 2023-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OCRImages',
            },
        ),
    ]
